//! ASCII → PS/2 scancode lookup tables.
//!
//! Two tables, one per scancode set:
//!   - **Set 1** (XT, 1981–84): originally generated by the 8048 in the
//!     IBM PC XT keyboard. Still used as the OS-visible format on
//!     AT/PS-2 when the 8042 has translation enabled (CCB bit 6).
//!   - **Set 2** (AT/PS-2 default, 1984+): the default emitted by
//!     AT/PS-2 keyboards. The 8042 may translate to Set 1 for the OS.
//!
//! The injector picks the table based on the classifier's
//! [`MachineClass`](vintage_kvm_signatures::MachineClass).
//!
//! Each table entry is one byte:
//!   - `0x00` = no mapping (caller skips the character).
//!   - non-zero = scancode value. The injector emits `[code]` for make
//!     and either `[0xF0, code]` (Set 2) or `[code | 0x80]` (Set 1)
//!     for break.
//!
//! Shifted characters (uppercase, punctuation that needs LSHIFT held)
//! are not in these tables; staying with lowercase ASCII + digits +
//! the unshifted punctuation set means the injector doesn't need to
//! track shift-key make/break interleaving or keyboard-LED state.

/// Set 2 scancode for `c` (ASCII), or 0 if unsupported. Used for
/// `MachineClass::At` and `MachineClass::Ps2`.
pub const fn ascii_to_set2(c: u8) -> u8 {
    SET2_TABLE[c as usize]
}

/// Set 1 scancode for `c` (ASCII), or 0 if unsupported. Used for
/// `MachineClass::Xt`.
pub const fn ascii_to_set1(c: u8) -> u8 {
    SET1_TABLE[c as usize]
}

const fn build_set2_table() -> [u8; 128] {
    let mut t = [0u8; 128];

    // Lowercase letters.
    t[b'a' as usize] = 0x1C;
    t[b'b' as usize] = 0x32;
    t[b'c' as usize] = 0x21;
    t[b'd' as usize] = 0x23;
    t[b'e' as usize] = 0x24;
    t[b'f' as usize] = 0x2B;
    t[b'g' as usize] = 0x34;
    t[b'h' as usize] = 0x33;
    t[b'i' as usize] = 0x43;
    t[b'j' as usize] = 0x3B;
    t[b'k' as usize] = 0x42;
    t[b'l' as usize] = 0x4B;
    t[b'm' as usize] = 0x3A;
    t[b'n' as usize] = 0x31;
    t[b'o' as usize] = 0x44;
    t[b'p' as usize] = 0x4D;
    t[b'q' as usize] = 0x15;
    t[b'r' as usize] = 0x2D;
    t[b's' as usize] = 0x1B;
    t[b't' as usize] = 0x2C;
    t[b'u' as usize] = 0x3C;
    t[b'v' as usize] = 0x2A;
    t[b'w' as usize] = 0x1D;
    t[b'x' as usize] = 0x22;
    t[b'y' as usize] = 0x35;
    t[b'z' as usize] = 0x1A;

    // Digits (top row, not numpad).
    t[b'0' as usize] = 0x45;
    t[b'1' as usize] = 0x16;
    t[b'2' as usize] = 0x1E;
    t[b'3' as usize] = 0x26;
    t[b'4' as usize] = 0x25;
    t[b'5' as usize] = 0x2E;
    t[b'6' as usize] = 0x36;
    t[b'7' as usize] = 0x3D;
    t[b'8' as usize] = 0x3E;
    t[b'9' as usize] = 0x46;

    // Whitespace + return + a few unshifted punctuation.
    t[b' ' as usize] = 0x29;
    t[b'\r' as usize] = 0x5A;
    t[b'\t' as usize] = 0x0D;
    t[b'\x08' as usize] = 0x66; // backspace
    t[b'-' as usize] = 0x4E;
    t[b'=' as usize] = 0x55;
    t[b'[' as usize] = 0x54;
    t[b']' as usize] = 0x5B;
    t[b';' as usize] = 0x4C;
    t[b'\'' as usize] = 0x52;
    t[b',' as usize] = 0x41;
    t[b'.' as usize] = 0x49;
    t[b'/' as usize] = 0x4A;
    t[b'`' as usize] = 0x0E;
    t[b'\\' as usize] = 0x5D;

    t
}

const SET2_TABLE: [u8; 128] = build_set2_table();

const fn build_set1_table() -> [u8; 128] {
    let mut t = [0u8; 128];

    // Lowercase letters (top row → home row → bottom row).
    t[b'q' as usize] = 0x10;
    t[b'w' as usize] = 0x11;
    t[b'e' as usize] = 0x12;
    t[b'r' as usize] = 0x13;
    t[b't' as usize] = 0x14;
    t[b'y' as usize] = 0x15;
    t[b'u' as usize] = 0x16;
    t[b'i' as usize] = 0x17;
    t[b'o' as usize] = 0x18;
    t[b'p' as usize] = 0x19;
    t[b'a' as usize] = 0x1E;
    t[b's' as usize] = 0x1F;
    t[b'd' as usize] = 0x20;
    t[b'f' as usize] = 0x21;
    t[b'g' as usize] = 0x22;
    t[b'h' as usize] = 0x23;
    t[b'j' as usize] = 0x24;
    t[b'k' as usize] = 0x25;
    t[b'l' as usize] = 0x26;
    t[b'z' as usize] = 0x2C;
    t[b'x' as usize] = 0x2D;
    t[b'c' as usize] = 0x2E;
    t[b'v' as usize] = 0x2F;
    t[b'b' as usize] = 0x30;
    t[b'n' as usize] = 0x31;
    t[b'm' as usize] = 0x32;

    // Digits.
    t[b'1' as usize] = 0x02;
    t[b'2' as usize] = 0x03;
    t[b'3' as usize] = 0x04;
    t[b'4' as usize] = 0x05;
    t[b'5' as usize] = 0x06;
    t[b'6' as usize] = 0x07;
    t[b'7' as usize] = 0x08;
    t[b'8' as usize] = 0x09;
    t[b'9' as usize] = 0x0A;
    t[b'0' as usize] = 0x0B;

    // Whitespace + return + unshifted punctuation.
    t[b' ' as usize] = 0x39;
    t[b'\r' as usize] = 0x1C;
    t[b'\t' as usize] = 0x0F;
    t[b'\x08' as usize] = 0x0E; // backspace
    t[b'-' as usize] = 0x0C;
    t[b'=' as usize] = 0x0D;
    t[b'[' as usize] = 0x1A;
    t[b']' as usize] = 0x1B;
    t[b';' as usize] = 0x27;
    t[b'\'' as usize] = 0x28;
    t[b'`' as usize] = 0x29;
    t[b'\\' as usize] = 0x2B;
    t[b',' as usize] = 0x33;
    t[b'.' as usize] = 0x34;
    t[b'/' as usize] = 0x35;

    t
}

const SET1_TABLE: [u8; 128] = build_set1_table();
